name: hack_club_gp
description: Manage your Hack Club GP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_staggered_animations: ^0.1.2
  material_design_icons_flutter: '^3.4.4895'

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^3.0.6

flutter:
  uses-material-design: true
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis/Regular.ttf

import_sorter:
  emojis: true
